// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/isometry/go-digicert-mpki/client/certificate_enrollment"
	"github.com/isometry/go-digicert-mpki/client/certificate_profile"
	"github.com/isometry/go-digicert-mpki/client/enroll_status"
	"github.com/isometry/go-digicert-mpki/client/hello"
	"github.com/isometry/go-digicert-mpki/client/search_certificate"
	"github.com/isometry/go-digicert-mpki/client/seat_management"
	"github.com/isometry/go-digicert-mpki/client/user_management"
)

// Default digicert mpki HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "pki-ws-rest.symauth.com"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/mpki"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new digicert mpki HTTP client.
func NewHTTPClient(formats strfmt.Registry) *DigicertMpki {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new digicert mpki HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *DigicertMpki {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new digicert mpki client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *DigicertMpki {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(DigicertMpki)
	cli.Transport = transport
	cli.CertificateEnrollment = certificate_enrollment.New(transport, formats)
	cli.CertificateProfile = certificate_profile.New(transport, formats)
	cli.EnrollStatus = enroll_status.New(transport, formats)
	cli.Hello = hello.New(transport, formats)
	cli.SearchCertificate = search_certificate.New(transport, formats)
	cli.SeatManagement = seat_management.New(transport, formats)
	cli.UserManagement = user_management.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// DigicertMpki is a client for digicert mpki
type DigicertMpki struct {
	CertificateEnrollment certificate_enrollment.ClientService

	CertificateProfile certificate_profile.ClientService

	EnrollStatus enroll_status.ClientService

	Hello hello.ClientService

	SearchCertificate search_certificate.ClientService

	SeatManagement seat_management.ClientService

	UserManagement user_management.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *DigicertMpki) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.CertificateEnrollment.SetTransport(transport)
	c.CertificateProfile.SetTransport(transport)
	c.EnrollStatus.SetTransport(transport)
	c.Hello.SetTransport(transport)
	c.SearchCertificate.SetTransport(transport)
	c.SeatManagement.SetTransport(transport)
	c.UserManagement.SetTransport(transport)
}
