// Code generated by go-swagger; DO NOT EDIT.

package certificate_profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAllProfilesParams creates a new GetAllProfilesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAllProfilesParams() *GetAllProfilesParams {
	return &GetAllProfilesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllProfilesParamsWithTimeout creates a new GetAllProfilesParams object
// with the ability to set a timeout on a request.
func NewGetAllProfilesParamsWithTimeout(timeout time.Duration) *GetAllProfilesParams {
	return &GetAllProfilesParams{
		timeout: timeout,
	}
}

// NewGetAllProfilesParamsWithContext creates a new GetAllProfilesParams object
// with the ability to set a context for a request.
func NewGetAllProfilesParamsWithContext(ctx context.Context) *GetAllProfilesParams {
	return &GetAllProfilesParams{
		Context: ctx,
	}
}

// NewGetAllProfilesParamsWithHTTPClient creates a new GetAllProfilesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAllProfilesParamsWithHTTPClient(client *http.Client) *GetAllProfilesParams {
	return &GetAllProfilesParams{
		HTTPClient: client,
	}
}

/* GetAllProfilesParams contains all the parameters to send to the API endpoint
   for the get all profiles operation.

   Typically these are written to a http.Request.
*/
type GetAllProfilesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get all profiles params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllProfilesParams) WithDefaults() *GetAllProfilesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get all profiles params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllProfilesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get all profiles params
func (o *GetAllProfilesParams) WithTimeout(timeout time.Duration) *GetAllProfilesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all profiles params
func (o *GetAllProfilesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all profiles params
func (o *GetAllProfilesParams) WithContext(ctx context.Context) *GetAllProfilesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all profiles params
func (o *GetAllProfilesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all profiles params
func (o *GetAllProfilesParams) WithHTTPClient(client *http.Client) *GetAllProfilesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all profiles params
func (o *GetAllProfilesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllProfilesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
