// Code generated by go-swagger; DO NOT EDIT.

package certificate_profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/isometry/go-digicert-mpki/models"
)

// GetAllProfilesReader is a Reader for the GetAllProfiles structure.
type GetAllProfilesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllProfilesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAllProfilesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetAllProfilesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAllProfilesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAllProfilesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAllProfilesOK creates a GetAllProfilesOK with default headers values
func NewGetAllProfilesOK() *GetAllProfilesOK {
	return &GetAllProfilesOK{}
}

/* GetAllProfilesOK describes a response with status code 200, with default header values.

OK
*/
type GetAllProfilesOK struct {
	Payload []*models.GetProfileResponse
}

func (o *GetAllProfilesOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/profile][%d] getAllProfilesOK  %+v", 200, o.Payload)
}
func (o *GetAllProfilesOK) GetPayload() []*models.GetProfileResponse {
	return o.Payload
}

func (o *GetAllProfilesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllProfilesUnauthorized creates a GetAllProfilesUnauthorized with default headers values
func NewGetAllProfilesUnauthorized() *GetAllProfilesUnauthorized {
	return &GetAllProfilesUnauthorized{}
}

/* GetAllProfilesUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAllProfilesUnauthorized struct {
}

func (o *GetAllProfilesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1/profile][%d] getAllProfilesUnauthorized ", 401)
}

func (o *GetAllProfilesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAllProfilesForbidden creates a GetAllProfilesForbidden with default headers values
func NewGetAllProfilesForbidden() *GetAllProfilesForbidden {
	return &GetAllProfilesForbidden{}
}

/* GetAllProfilesForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetAllProfilesForbidden struct {
}

func (o *GetAllProfilesForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1/profile][%d] getAllProfilesForbidden ", 403)
}

func (o *GetAllProfilesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAllProfilesNotFound creates a GetAllProfilesNotFound with default headers values
func NewGetAllProfilesNotFound() *GetAllProfilesNotFound {
	return &GetAllProfilesNotFound{}
}

/* GetAllProfilesNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetAllProfilesNotFound struct {
}

func (o *GetAllProfilesNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/profile][%d] getAllProfilesNotFound ", 404)
}

func (o *GetAllProfilesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
