// Code generated by go-swagger; DO NOT EDIT.

package certificate_enrollment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/isometry/go-digicert-mpki/models"
)

// NewEnrollCertificateParams creates a new EnrollCertificateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEnrollCertificateParams() *EnrollCertificateParams {
	return &EnrollCertificateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEnrollCertificateParamsWithTimeout creates a new EnrollCertificateParams object
// with the ability to set a timeout on a request.
func NewEnrollCertificateParamsWithTimeout(timeout time.Duration) *EnrollCertificateParams {
	return &EnrollCertificateParams{
		timeout: timeout,
	}
}

// NewEnrollCertificateParamsWithContext creates a new EnrollCertificateParams object
// with the ability to set a context for a request.
func NewEnrollCertificateParamsWithContext(ctx context.Context) *EnrollCertificateParams {
	return &EnrollCertificateParams{
		Context: ctx,
	}
}

// NewEnrollCertificateParamsWithHTTPClient creates a new EnrollCertificateParams object
// with the ability to set a custom HTTPClient for a request.
func NewEnrollCertificateParamsWithHTTPClient(client *http.Client) *EnrollCertificateParams {
	return &EnrollCertificateParams{
		HTTPClient: client,
	}
}

/* EnrollCertificateParams contains all the parameters to send to the API endpoint
   for the enroll certificate operation.

   Typically these are written to a http.Request.
*/
type EnrollCertificateParams struct {

	/* EnrollCertificateRequest.

	   enrollCertificateRequest
	*/
	EnrollCertificateRequest *models.RequestCertificateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the enroll certificate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EnrollCertificateParams) WithDefaults() *EnrollCertificateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the enroll certificate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EnrollCertificateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the enroll certificate params
func (o *EnrollCertificateParams) WithTimeout(timeout time.Duration) *EnrollCertificateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the enroll certificate params
func (o *EnrollCertificateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the enroll certificate params
func (o *EnrollCertificateParams) WithContext(ctx context.Context) *EnrollCertificateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the enroll certificate params
func (o *EnrollCertificateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the enroll certificate params
func (o *EnrollCertificateParams) WithHTTPClient(client *http.Client) *EnrollCertificateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the enroll certificate params
func (o *EnrollCertificateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnrollCertificateRequest adds the enrollCertificateRequest to the enroll certificate params
func (o *EnrollCertificateParams) WithEnrollCertificateRequest(enrollCertificateRequest *models.RequestCertificateRequest) *EnrollCertificateParams {
	o.SetEnrollCertificateRequest(enrollCertificateRequest)
	return o
}

// SetEnrollCertificateRequest adds the enrollCertificateRequest to the enroll certificate params
func (o *EnrollCertificateParams) SetEnrollCertificateRequest(enrollCertificateRequest *models.RequestCertificateRequest) {
	o.EnrollCertificateRequest = enrollCertificateRequest
}

// WriteToRequest writes these params to a swagger request
func (o *EnrollCertificateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.EnrollCertificateRequest != nil {
		if err := r.SetBodyParam(o.EnrollCertificateRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
