// Code generated by go-swagger; DO NOT EDIT.

package certificate_enrollment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUnRevokeCertificateParams creates a new UnRevokeCertificateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUnRevokeCertificateParams() *UnRevokeCertificateParams {
	return &UnRevokeCertificateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUnRevokeCertificateParamsWithTimeout creates a new UnRevokeCertificateParams object
// with the ability to set a timeout on a request.
func NewUnRevokeCertificateParamsWithTimeout(timeout time.Duration) *UnRevokeCertificateParams {
	return &UnRevokeCertificateParams{
		timeout: timeout,
	}
}

// NewUnRevokeCertificateParamsWithContext creates a new UnRevokeCertificateParams object
// with the ability to set a context for a request.
func NewUnRevokeCertificateParamsWithContext(ctx context.Context) *UnRevokeCertificateParams {
	return &UnRevokeCertificateParams{
		Context: ctx,
	}
}

// NewUnRevokeCertificateParamsWithHTTPClient creates a new UnRevokeCertificateParams object
// with the ability to set a custom HTTPClient for a request.
func NewUnRevokeCertificateParamsWithHTTPClient(client *http.Client) *UnRevokeCertificateParams {
	return &UnRevokeCertificateParams{
		HTTPClient: client,
	}
}

/* UnRevokeCertificateParams contains all the parameters to send to the API endpoint
   for the un revoke certificate operation.

   Typically these are written to a http.Request.
*/
type UnRevokeCertificateParams struct {

	/* SerialNumber.

	   serialNumber
	*/
	SerialNumber string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the un revoke certificate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UnRevokeCertificateParams) WithDefaults() *UnRevokeCertificateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the un revoke certificate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UnRevokeCertificateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the un revoke certificate params
func (o *UnRevokeCertificateParams) WithTimeout(timeout time.Duration) *UnRevokeCertificateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the un revoke certificate params
func (o *UnRevokeCertificateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the un revoke certificate params
func (o *UnRevokeCertificateParams) WithContext(ctx context.Context) *UnRevokeCertificateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the un revoke certificate params
func (o *UnRevokeCertificateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the un revoke certificate params
func (o *UnRevokeCertificateParams) WithHTTPClient(client *http.Client) *UnRevokeCertificateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the un revoke certificate params
func (o *UnRevokeCertificateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSerialNumber adds the serialNumber to the un revoke certificate params
func (o *UnRevokeCertificateParams) WithSerialNumber(serialNumber string) *UnRevokeCertificateParams {
	o.SetSerialNumber(serialNumber)
	return o
}

// SetSerialNumber adds the serialNumber to the un revoke certificate params
func (o *UnRevokeCertificateParams) SetSerialNumber(serialNumber string) {
	o.SerialNumber = serialNumber
}

// WriteToRequest writes these params to a swagger request
func (o *UnRevokeCertificateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param serialNumber
	if err := r.SetPathParam("serialNumber", o.SerialNumber); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
