// Code generated by go-swagger; DO NOT EDIT.

package search_certificate

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/isometry/go-digicert-mpki/models"
)

// NewSearchCertParams creates a new SearchCertParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSearchCertParams() *SearchCertParams {
	return &SearchCertParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSearchCertParamsWithTimeout creates a new SearchCertParams object
// with the ability to set a timeout on a request.
func NewSearchCertParamsWithTimeout(timeout time.Duration) *SearchCertParams {
	return &SearchCertParams{
		timeout: timeout,
	}
}

// NewSearchCertParamsWithContext creates a new SearchCertParams object
// with the ability to set a context for a request.
func NewSearchCertParamsWithContext(ctx context.Context) *SearchCertParams {
	return &SearchCertParams{
		Context: ctx,
	}
}

// NewSearchCertParamsWithHTTPClient creates a new SearchCertParams object
// with the ability to set a custom HTTPClient for a request.
func NewSearchCertParamsWithHTTPClient(client *http.Client) *SearchCertParams {
	return &SearchCertParams{
		HTTPClient: client,
	}
}

/* SearchCertParams contains all the parameters to send to the API endpoint
   for the search cert operation.

   Typically these are written to a http.Request.
*/
type SearchCertParams struct {

	/* SearchReq.

	   searchReq
	*/
	SearchReq *models.SearchCertificateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the search cert params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchCertParams) WithDefaults() *SearchCertParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the search cert params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchCertParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the search cert params
func (o *SearchCertParams) WithTimeout(timeout time.Duration) *SearchCertParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search cert params
func (o *SearchCertParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search cert params
func (o *SearchCertParams) WithContext(ctx context.Context) *SearchCertParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search cert params
func (o *SearchCertParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search cert params
func (o *SearchCertParams) WithHTTPClient(client *http.Client) *SearchCertParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search cert params
func (o *SearchCertParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSearchReq adds the searchReq to the search cert params
func (o *SearchCertParams) WithSearchReq(searchReq *models.SearchCertificateRequest) *SearchCertParams {
	o.SetSearchReq(searchReq)
	return o
}

// SetSearchReq adds the searchReq to the search cert params
func (o *SearchCertParams) SetSearchReq(searchReq *models.SearchCertificateRequest) {
	o.SearchReq = searchReq
}

// WriteToRequest writes these params to a swagger request
func (o *SearchCertParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.SearchReq != nil {
		if err := r.SetBodyParam(o.SearchReq); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
