// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/isometry/go-digicert-mpki/client/certificate_enrollment"
	"github.com/isometry/go-digicert-mpki/models"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationCertificateEnrollmentEnrollCertificateCmd returns a cmd to handle operation enrollCertificate
func makeOperationCertificateEnrollmentEnrollCertificateCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "enrollCertificate",
		Short: ``,
		RunE:  runOperationCertificateEnrollmentEnrollCertificate,
	}

	if err := registerOperationCertificateEnrollmentEnrollCertificateParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationCertificateEnrollmentEnrollCertificate uses cmd flags to call endpoint api
func runOperationCertificateEnrollmentEnrollCertificate(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := certificate_enrollment.NewEnrollCertificateParams()
	if err, _ := retrieveOperationCertificateEnrollmentEnrollCertificateEnrollCertificateRequestFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationCertificateEnrollmentEnrollCertificateResult(appCli.CertificateEnrollment.EnrollCertificate(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationCertificateEnrollmentEnrollCertificateParamFlags registers all flags needed to fill params
func registerOperationCertificateEnrollmentEnrollCertificateParamFlags(cmd *cobra.Command) error {
	if err := registerOperationCertificateEnrollmentEnrollCertificateEnrollCertificateRequestParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationCertificateEnrollmentEnrollCertificateEnrollCertificateRequestParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var enrollCertificateRequestFlagName string
	if cmdPrefix == "" {
		enrollCertificateRequestFlagName = "enrollCertificateRequest"
	} else {
		enrollCertificateRequestFlagName = fmt.Sprintf("%v.enrollCertificateRequest", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(enrollCertificateRequestFlagName, "", "Optional json string for [enrollCertificateRequest]. enrollCertificateRequest")

	// add flags for body
	if err := registerModelRequestCertificateRequestFlags(0, "requestCertificateRequest", cmd); err != nil {
		return err
	}

	return nil
}

func retrieveOperationCertificateEnrollmentEnrollCertificateEnrollCertificateRequestFlag(m *certificate_enrollment.EnrollCertificateParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("enrollCertificateRequest") {
		// Read enrollCertificateRequest string from cmd and unmarshal
		enrollCertificateRequestValueStr, err := cmd.Flags().GetString("enrollCertificateRequest")
		if err != nil {
			return err, false
		}

		enrollCertificateRequestValue := models.RequestCertificateRequest{}
		if err := json.Unmarshal([]byte(enrollCertificateRequestValueStr), &enrollCertificateRequestValue); err != nil {
			return fmt.Errorf("cannot unmarshal enrollCertificateRequest string in models.RequestCertificateRequest: %v", err), false
		}
		m.EnrollCertificateRequest = &enrollCertificateRequestValue
	}
	enrollCertificateRequestValueModel := m.EnrollCertificateRequest
	if swag.IsZero(enrollCertificateRequestValueModel) {
		enrollCertificateRequestValueModel = &models.RequestCertificateRequest{}
	}
	err, added := retrieveModelRequestCertificateRequestFlags(0, enrollCertificateRequestValueModel, "requestCertificateRequest", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.EnrollCertificateRequest = enrollCertificateRequestValueModel
	}
	if dryRun && debug {

		enrollCertificateRequestValueDebugBytes, err := json.Marshal(m.EnrollCertificateRequest)
		if err != nil {
			return err, false
		}
		logDebugf("EnrollCertificateRequest dry-run payload: %v", string(enrollCertificateRequestValueDebugBytes))
	}
	retAdded = retAdded || added

	return nil, retAdded
}

// parseOperationCertificateEnrollmentEnrollCertificateResult parses request result and return the string content
func parseOperationCertificateEnrollmentEnrollCertificateResult(resp0 *certificate_enrollment.EnrollCertificateOK, resp1 *certificate_enrollment.EnrollCertificateCreated, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*certificate_enrollment.EnrollCertificateOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		// Non schema case: warning enrollCertificateCreated is not supported

		// Non schema case: warning enrollCertificateUnauthorized is not supported

		// Non schema case: warning enrollCertificateForbidden is not supported

		// Non schema case: warning enrollCertificateNotFound is not supported

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	// warning: non schema response enrollCertificateCreated is not supported by go-swagger cli yet.

	return "", nil
}
