// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/isometry/go-digicert-mpki/client/seat_management"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationSeatManagementGetSeatCmd returns a cmd to handle operation getSeat
func makeOperationSeatManagementGetSeatCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "getSeat",
		Short: ``,
		RunE:  runOperationSeatManagementGetSeat,
	}

	if err := registerOperationSeatManagementGetSeatParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationSeatManagementGetSeat uses cmd flags to call endpoint api
func runOperationSeatManagementGetSeat(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := seat_management.NewGetSeatParams()
	if err, _ := retrieveOperationSeatManagementGetSeatSeatIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationSeatManagementGetSeatResult(appCli.SeatManagement.GetSeat(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationSeatManagementGetSeatParamFlags registers all flags needed to fill params
func registerOperationSeatManagementGetSeatParamFlags(cmd *cobra.Command) error {
	if err := registerOperationSeatManagementGetSeatSeatIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationSeatManagementGetSeatSeatIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	seatIdDescription := `Required. seatId`

	var seatIdFlagName string
	if cmdPrefix == "" {
		seatIdFlagName = "seatId"
	} else {
		seatIdFlagName = fmt.Sprintf("%v.seatId", cmdPrefix)
	}

	var seatIdFlagDefault string

	_ = cmd.PersistentFlags().String(seatIdFlagName, seatIdFlagDefault, seatIdDescription)

	return nil
}

func retrieveOperationSeatManagementGetSeatSeatIDFlag(m *seat_management.GetSeatParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("seatId") {

		var seatIdFlagName string
		if cmdPrefix == "" {
			seatIdFlagName = "seatId"
		} else {
			seatIdFlagName = fmt.Sprintf("%v.seatId", cmdPrefix)
		}

		seatIdFlagValue, err := cmd.Flags().GetString(seatIdFlagName)
		if err != nil {
			return err, false
		}
		m.SeatID = seatIdFlagValue

	}
	return nil, retAdded
}

// parseOperationSeatManagementGetSeatResult parses request result and return the string content
func parseOperationSeatManagementGetSeatResult(resp0 *seat_management.GetSeatOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*seat_management.GetSeatOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		// Non schema case: warning getSeatUnauthorized is not supported

		// Non schema case: warning getSeatForbidden is not supported

		// Non schema case: warning getSeatNotFound is not supported

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
