// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/isometry/go-digicert-mpki/client/certificate_enrollment"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationCertificateEnrollmentGetCertificateCmd returns a cmd to handle operation getCertificate
func makeOperationCertificateEnrollmentGetCertificateCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "getCertificate",
		Short: ``,
		RunE:  runOperationCertificateEnrollmentGetCertificate,
	}

	if err := registerOperationCertificateEnrollmentGetCertificateParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationCertificateEnrollmentGetCertificate uses cmd flags to call endpoint api
func runOperationCertificateEnrollmentGetCertificate(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := certificate_enrollment.NewGetCertificateParams()
	if err, _ := retrieveOperationCertificateEnrollmentGetCertificateSerialNumberFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationCertificateEnrollmentGetCertificateResult(appCli.CertificateEnrollment.GetCertificate(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationCertificateEnrollmentGetCertificateParamFlags registers all flags needed to fill params
func registerOperationCertificateEnrollmentGetCertificateParamFlags(cmd *cobra.Command) error {
	if err := registerOperationCertificateEnrollmentGetCertificateSerialNumberParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationCertificateEnrollmentGetCertificateSerialNumberParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	serialNumberDescription := `Required. serialNumber`

	var serialNumberFlagName string
	if cmdPrefix == "" {
		serialNumberFlagName = "serialNumber"
	} else {
		serialNumberFlagName = fmt.Sprintf("%v.serialNumber", cmdPrefix)
	}

	var serialNumberFlagDefault string

	_ = cmd.PersistentFlags().String(serialNumberFlagName, serialNumberFlagDefault, serialNumberDescription)

	return nil
}

func retrieveOperationCertificateEnrollmentGetCertificateSerialNumberFlag(m *certificate_enrollment.GetCertificateParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("serialNumber") {

		var serialNumberFlagName string
		if cmdPrefix == "" {
			serialNumberFlagName = "serialNumber"
		} else {
			serialNumberFlagName = fmt.Sprintf("%v.serialNumber", cmdPrefix)
		}

		serialNumberFlagValue, err := cmd.Flags().GetString(serialNumberFlagName)
		if err != nil {
			return err, false
		}
		m.SerialNumber = serialNumberFlagValue

	}
	return nil, retAdded
}

// parseOperationCertificateEnrollmentGetCertificateResult parses request result and return the string content
func parseOperationCertificateEnrollmentGetCertificateResult(resp0 *certificate_enrollment.GetCertificateOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*certificate_enrollment.GetCertificateOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		// Non schema case: warning getCertificateUnauthorized is not supported

		// Non schema case: warning getCertificateForbidden is not supported

		// Non schema case: warning getCertificateNotFound is not supported

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
