// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/isometry/go-digicert-mpki/models"
	"github.com/spf13/cobra"
)

// Schema cli for Issuer

// register flags to command
func registerModelIssuerFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerIssuerCertificate(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerIssuerChain(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerIssuerRoot(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerIssuerSerialNumber(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerIssuerSubjectDn(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerIssuerCertificate(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: primitive certificate strfmt.Base64 is not supported by go-swagger cli yet

	return nil
}

func registerIssuerChain(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: chain []*CertificateInfo array type is not supported by go-swagger cli yet

	return nil
}

func registerIssuerRoot(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	rootDescription := ``

	var rootFlagName string
	if cmdPrefix == "" {
		rootFlagName = "root"
	} else {
		rootFlagName = fmt.Sprintf("%v.root", cmdPrefix)
	}

	var rootFlagDefault bool

	_ = cmd.PersistentFlags().Bool(rootFlagName, rootFlagDefault, rootDescription)

	return nil
}

func registerIssuerSerialNumber(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	serialNumberDescription := ``

	var serialNumberFlagName string
	if cmdPrefix == "" {
		serialNumberFlagName = "serial_number"
	} else {
		serialNumberFlagName = fmt.Sprintf("%v.serial_number", cmdPrefix)
	}

	var serialNumberFlagDefault string

	_ = cmd.PersistentFlags().String(serialNumberFlagName, serialNumberFlagDefault, serialNumberDescription)

	return nil
}

func registerIssuerSubjectDn(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	subjectDnDescription := ``

	var subjectDnFlagName string
	if cmdPrefix == "" {
		subjectDnFlagName = "subject_dn"
	} else {
		subjectDnFlagName = fmt.Sprintf("%v.subject_dn", cmdPrefix)
	}

	var subjectDnFlagDefault string

	_ = cmd.PersistentFlags().String(subjectDnFlagName, subjectDnFlagDefault, subjectDnDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelIssuerFlags(depth int, m *models.Issuer, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, certificateAdded := retrieveIssuerCertificateFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || certificateAdded

	err, chainAdded := retrieveIssuerChainFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || chainAdded

	err, rootAdded := retrieveIssuerRootFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || rootAdded

	err, serialNumberAdded := retrieveIssuerSerialNumberFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || serialNumberAdded

	err, subjectDnAdded := retrieveIssuerSubjectDnFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || subjectDnAdded

	return nil, retAdded
}

func retrieveIssuerCertificateFlags(depth int, m *models.Issuer, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	certificateFlagName := fmt.Sprintf("%v.certificate", cmdPrefix)
	if cmd.Flags().Changed(certificateFlagName) {

		// warning: primitive certificate strfmt.Base64 is not supported by go-swagger cli yet

		retAdded = true
	}

	return nil, retAdded
}

func retrieveIssuerChainFlags(depth int, m *models.Issuer, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	chainFlagName := fmt.Sprintf("%v.chain", cmdPrefix)
	if cmd.Flags().Changed(chainFlagName) {
		// warning: chain array type []*CertificateInfo is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveIssuerRootFlags(depth int, m *models.Issuer, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	rootFlagName := fmt.Sprintf("%v.root", cmdPrefix)
	if cmd.Flags().Changed(rootFlagName) {

		var rootFlagName string
		if cmdPrefix == "" {
			rootFlagName = "root"
		} else {
			rootFlagName = fmt.Sprintf("%v.root", cmdPrefix)
		}

		rootFlagValue, err := cmd.Flags().GetBool(rootFlagName)
		if err != nil {
			return err, false
		}
		m.Root = rootFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveIssuerSerialNumberFlags(depth int, m *models.Issuer, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	serialNumberFlagName := fmt.Sprintf("%v.serial_number", cmdPrefix)
	if cmd.Flags().Changed(serialNumberFlagName) {

		var serialNumberFlagName string
		if cmdPrefix == "" {
			serialNumberFlagName = "serial_number"
		} else {
			serialNumberFlagName = fmt.Sprintf("%v.serial_number", cmdPrefix)
		}

		serialNumberFlagValue, err := cmd.Flags().GetString(serialNumberFlagName)
		if err != nil {
			return err, false
		}
		m.SerialNumber = serialNumberFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveIssuerSubjectDnFlags(depth int, m *models.Issuer, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	subjectDnFlagName := fmt.Sprintf("%v.subject_dn", cmdPrefix)
	if cmd.Flags().Changed(subjectDnFlagName) {

		var subjectDnFlagName string
		if cmdPrefix == "" {
			subjectDnFlagName = "subject_dn"
		} else {
			subjectDnFlagName = fmt.Sprintf("%v.subject_dn", cmdPrefix)
		}

		subjectDnFlagValue, err := cmd.Flags().GetString(subjectDnFlagName)
		if err != nil {
			return err, false
		}
		m.SubjectDn = subjectDnFlagValue

		retAdded = true
	}

	return nil, retAdded
}
