// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/isometry/go-digicert-mpki/models"
	"github.com/spf13/cobra"
)

// Schema cli for SanAttributes

// register flags to command
func registerModelSanAttributesFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerSanAttributesCustomAttributes(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerSanAttributesDirectoryName(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerSanAttributesDNSName(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerSanAttributesIPAddress(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerSanAttributesOtherName(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerSanAttributesRegisteredID(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerSanAttributesRfc822Name(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerSanAttributesUserPrincipalName(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerSanAttributesCustomAttributes(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: custom_attributes map[string]string map type is not supported by go-swagger cli yet

	return nil
}

func registerSanAttributesDirectoryName(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	directoryNameDescription := ``

	var directoryNameFlagName string
	if cmdPrefix == "" {
		directoryNameFlagName = "directory_name"
	} else {
		directoryNameFlagName = fmt.Sprintf("%v.directory_name", cmdPrefix)
	}

	var directoryNameFlagDefault string

	_ = cmd.PersistentFlags().String(directoryNameFlagName, directoryNameFlagDefault, directoryNameDescription)

	return nil
}

func registerSanAttributesDNSName(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: dns_name []*Attribute array type is not supported by go-swagger cli yet

	return nil
}

func registerSanAttributesIPAddress(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: ip_address []*Attribute array type is not supported by go-swagger cli yet

	return nil
}

func registerSanAttributesOtherName(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: other_name []*Attribute array type is not supported by go-swagger cli yet

	return nil
}

func registerSanAttributesRegisteredID(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: registered_id []*Attribute array type is not supported by go-swagger cli yet

	return nil
}

func registerSanAttributesRfc822Name(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: rfc822_name []*Attribute array type is not supported by go-swagger cli yet

	return nil
}

func registerSanAttributesUserPrincipalName(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: user_principal_name []*Attribute array type is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelSanAttributesFlags(depth int, m *models.SanAttributes, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, customAttributesAdded := retrieveSanAttributesCustomAttributesFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || customAttributesAdded

	err, directoryNameAdded := retrieveSanAttributesDirectoryNameFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || directoryNameAdded

	err, dnsNameAdded := retrieveSanAttributesDNSNameFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || dnsNameAdded

	err, ipAddressAdded := retrieveSanAttributesIPAddressFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ipAddressAdded

	err, otherNameAdded := retrieveSanAttributesOtherNameFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || otherNameAdded

	err, registeredIdAdded := retrieveSanAttributesRegisteredIDFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || registeredIdAdded

	err, rfc822NameAdded := retrieveSanAttributesRfc822NameFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || rfc822NameAdded

	err, userPrincipalNameAdded := retrieveSanAttributesUserPrincipalNameFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || userPrincipalNameAdded

	return nil, retAdded
}

func retrieveSanAttributesCustomAttributesFlags(depth int, m *models.SanAttributes, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	customAttributesFlagName := fmt.Sprintf("%v.custom_attributes", cmdPrefix)
	if cmd.Flags().Changed(customAttributesFlagName) {
		// warning: custom_attributes map type map[string]string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveSanAttributesDirectoryNameFlags(depth int, m *models.SanAttributes, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	directoryNameFlagName := fmt.Sprintf("%v.directory_name", cmdPrefix)
	if cmd.Flags().Changed(directoryNameFlagName) {

		var directoryNameFlagName string
		if cmdPrefix == "" {
			directoryNameFlagName = "directory_name"
		} else {
			directoryNameFlagName = fmt.Sprintf("%v.directory_name", cmdPrefix)
		}

		directoryNameFlagValue, err := cmd.Flags().GetString(directoryNameFlagName)
		if err != nil {
			return err, false
		}
		m.DirectoryName = directoryNameFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveSanAttributesDNSNameFlags(depth int, m *models.SanAttributes, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	dnsNameFlagName := fmt.Sprintf("%v.dns_name", cmdPrefix)
	if cmd.Flags().Changed(dnsNameFlagName) {
		// warning: dns_name array type []*Attribute is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveSanAttributesIPAddressFlags(depth int, m *models.SanAttributes, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	ipAddressFlagName := fmt.Sprintf("%v.ip_address", cmdPrefix)
	if cmd.Flags().Changed(ipAddressFlagName) {
		// warning: ip_address array type []*Attribute is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveSanAttributesOtherNameFlags(depth int, m *models.SanAttributes, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	otherNameFlagName := fmt.Sprintf("%v.other_name", cmdPrefix)
	if cmd.Flags().Changed(otherNameFlagName) {
		// warning: other_name array type []*Attribute is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveSanAttributesRegisteredIDFlags(depth int, m *models.SanAttributes, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	registeredIdFlagName := fmt.Sprintf("%v.registered_id", cmdPrefix)
	if cmd.Flags().Changed(registeredIdFlagName) {
		// warning: registered_id array type []*Attribute is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveSanAttributesRfc822NameFlags(depth int, m *models.SanAttributes, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	rfc822NameFlagName := fmt.Sprintf("%v.rfc822_name", cmdPrefix)
	if cmd.Flags().Changed(rfc822NameFlagName) {
		// warning: rfc822_name array type []*Attribute is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveSanAttributesUserPrincipalNameFlags(depth int, m *models.SanAttributes, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	userPrincipalNameFlagName := fmt.Sprintf("%v.user_principal_name", cmdPrefix)
	if cmd.Flags().Changed(userPrincipalNameFlagName) {
		// warning: user_principal_name array type []*Attribute is not supported by go-swagger cli yet
	}

	return nil, retAdded
}
