// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/isometry/go-digicert-mpki/models"
	"github.com/spf13/cobra"
)

// Schema cli for Seat

// register flags to command
func registerModelSeatFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerSeatEmail(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerSeatSeatID(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerSeatSeatName(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerSeatEmail(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	emailDescription := ``

	var emailFlagName string
	if cmdPrefix == "" {
		emailFlagName = "email"
	} else {
		emailFlagName = fmt.Sprintf("%v.email", cmdPrefix)
	}

	var emailFlagDefault string

	_ = cmd.PersistentFlags().String(emailFlagName, emailFlagDefault, emailDescription)

	return nil
}

func registerSeatSeatID(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	seatIdDescription := ``

	var seatIdFlagName string
	if cmdPrefix == "" {
		seatIdFlagName = "seat_id"
	} else {
		seatIdFlagName = fmt.Sprintf("%v.seat_id", cmdPrefix)
	}

	var seatIdFlagDefault string

	_ = cmd.PersistentFlags().String(seatIdFlagName, seatIdFlagDefault, seatIdDescription)

	return nil
}

func registerSeatSeatName(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	seatNameDescription := ``

	var seatNameFlagName string
	if cmdPrefix == "" {
		seatNameFlagName = "seat_name"
	} else {
		seatNameFlagName = fmt.Sprintf("%v.seat_name", cmdPrefix)
	}

	var seatNameFlagDefault string

	_ = cmd.PersistentFlags().String(seatNameFlagName, seatNameFlagDefault, seatNameDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelSeatFlags(depth int, m *models.Seat, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, emailAdded := retrieveSeatEmailFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || emailAdded

	err, seatIdAdded := retrieveSeatSeatIDFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || seatIdAdded

	err, seatNameAdded := retrieveSeatSeatNameFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || seatNameAdded

	return nil, retAdded
}

func retrieveSeatEmailFlags(depth int, m *models.Seat, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	emailFlagName := fmt.Sprintf("%v.email", cmdPrefix)
	if cmd.Flags().Changed(emailFlagName) {

		var emailFlagName string
		if cmdPrefix == "" {
			emailFlagName = "email"
		} else {
			emailFlagName = fmt.Sprintf("%v.email", cmdPrefix)
		}

		emailFlagValue, err := cmd.Flags().GetString(emailFlagName)
		if err != nil {
			return err, false
		}
		m.Email = emailFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveSeatSeatIDFlags(depth int, m *models.Seat, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	seatIdFlagName := fmt.Sprintf("%v.seat_id", cmdPrefix)
	if cmd.Flags().Changed(seatIdFlagName) {

		var seatIdFlagName string
		if cmdPrefix == "" {
			seatIdFlagName = "seat_id"
		} else {
			seatIdFlagName = fmt.Sprintf("%v.seat_id", cmdPrefix)
		}

		seatIdFlagValue, err := cmd.Flags().GetString(seatIdFlagName)
		if err != nil {
			return err, false
		}
		m.SeatID = seatIdFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveSeatSeatNameFlags(depth int, m *models.Seat, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	seatNameFlagName := fmt.Sprintf("%v.seat_name", cmdPrefix)
	if cmd.Flags().Changed(seatNameFlagName) {

		var seatNameFlagName string
		if cmdPrefix == "" {
			seatNameFlagName = "seat_name"
		} else {
			seatNameFlagName = fmt.Sprintf("%v.seat_name", cmdPrefix)
		}

		seatNameFlagValue, err := cmd.Flags().GetString(seatNameFlagName)
		if err != nil {
			return err, false
		}
		m.SeatName = seatNameFlagValue

		retAdded = true
	}

	return nil, retAdded
}
