// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/isometry/go-digicert-mpki/client/certificate_enrollment"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationCertificateEnrollmentUnRevokeCertificateCmd returns a cmd to handle operation unRevokeCertificate
func makeOperationCertificateEnrollmentUnRevokeCertificateCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "unRevokeCertificate",
		Short: ``,
		RunE:  runOperationCertificateEnrollmentUnRevokeCertificate,
	}

	if err := registerOperationCertificateEnrollmentUnRevokeCertificateParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationCertificateEnrollmentUnRevokeCertificate uses cmd flags to call endpoint api
func runOperationCertificateEnrollmentUnRevokeCertificate(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := certificate_enrollment.NewUnRevokeCertificateParams()
	if err, _ := retrieveOperationCertificateEnrollmentUnRevokeCertificateSerialNumberFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationCertificateEnrollmentUnRevokeCertificateResult(appCli.CertificateEnrollment.UnRevokeCertificate(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationCertificateEnrollmentUnRevokeCertificateParamFlags registers all flags needed to fill params
func registerOperationCertificateEnrollmentUnRevokeCertificateParamFlags(cmd *cobra.Command) error {
	if err := registerOperationCertificateEnrollmentUnRevokeCertificateSerialNumberParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationCertificateEnrollmentUnRevokeCertificateSerialNumberParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	serialNumberDescription := `Required. serialNumber`

	var serialNumberFlagName string
	if cmdPrefix == "" {
		serialNumberFlagName = "serialNumber"
	} else {
		serialNumberFlagName = fmt.Sprintf("%v.serialNumber", cmdPrefix)
	}

	var serialNumberFlagDefault string

	_ = cmd.PersistentFlags().String(serialNumberFlagName, serialNumberFlagDefault, serialNumberDescription)

	return nil
}

func retrieveOperationCertificateEnrollmentUnRevokeCertificateSerialNumberFlag(m *certificate_enrollment.UnRevokeCertificateParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("serialNumber") {

		var serialNumberFlagName string
		if cmdPrefix == "" {
			serialNumberFlagName = "serialNumber"
		} else {
			serialNumberFlagName = fmt.Sprintf("%v.serialNumber", cmdPrefix)
		}

		serialNumberFlagValue, err := cmd.Flags().GetString(serialNumberFlagName)
		if err != nil {
			return err, false
		}
		m.SerialNumber = serialNumberFlagValue

	}
	return nil, retAdded
}

// parseOperationCertificateEnrollmentUnRevokeCertificateResult parses request result and return the string content
func parseOperationCertificateEnrollmentUnRevokeCertificateResult(resp0 *certificate_enrollment.UnRevokeCertificateOK, resp1 *certificate_enrollment.UnRevokeCertificateNoContent, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*certificate_enrollment.UnRevokeCertificateOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		// Non schema case: warning unRevokeCertificateNoContent is not supported

		// Non schema case: warning unRevokeCertificateUnauthorized is not supported

		// Non schema case: warning unRevokeCertificateForbidden is not supported

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	// warning: non schema response unRevokeCertificateNoContent is not supported by go-swagger cli yet.

	return "", nil
}
