// Code generated by go-swagger; DO NOT EDIT.

package seat_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/isometry/go-digicert-mpki/models"
)

// NewCreateSeatParams creates a new CreateSeatParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateSeatParams() *CreateSeatParams {
	return &CreateSeatParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateSeatParamsWithTimeout creates a new CreateSeatParams object
// with the ability to set a timeout on a request.
func NewCreateSeatParamsWithTimeout(timeout time.Duration) *CreateSeatParams {
	return &CreateSeatParams{
		timeout: timeout,
	}
}

// NewCreateSeatParamsWithContext creates a new CreateSeatParams object
// with the ability to set a context for a request.
func NewCreateSeatParamsWithContext(ctx context.Context) *CreateSeatParams {
	return &CreateSeatParams{
		Context: ctx,
	}
}

// NewCreateSeatParamsWithHTTPClient creates a new CreateSeatParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateSeatParamsWithHTTPClient(client *http.Client) *CreateSeatParams {
	return &CreateSeatParams{
		HTTPClient: client,
	}
}

/* CreateSeatParams contains all the parameters to send to the API endpoint
   for the create seat operation.

   Typically these are written to a http.Request.
*/
type CreateSeatParams struct {

	/* CreateSeatRequest.

	   createSeatRequest
	*/
	CreateSeatRequest *models.CreateSeatRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create seat params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateSeatParams) WithDefaults() *CreateSeatParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create seat params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateSeatParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create seat params
func (o *CreateSeatParams) WithTimeout(timeout time.Duration) *CreateSeatParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create seat params
func (o *CreateSeatParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create seat params
func (o *CreateSeatParams) WithContext(ctx context.Context) *CreateSeatParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create seat params
func (o *CreateSeatParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create seat params
func (o *CreateSeatParams) WithHTTPClient(client *http.Client) *CreateSeatParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create seat params
func (o *CreateSeatParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCreateSeatRequest adds the createSeatRequest to the create seat params
func (o *CreateSeatParams) WithCreateSeatRequest(createSeatRequest *models.CreateSeatRequest) *CreateSeatParams {
	o.SetCreateSeatRequest(createSeatRequest)
	return o
}

// SetCreateSeatRequest adds the createSeatRequest to the create seat params
func (o *CreateSeatParams) SetCreateSeatRequest(createSeatRequest *models.CreateSeatRequest) {
	o.CreateSeatRequest = createSeatRequest
}

// WriteToRequest writes these params to a swagger request
func (o *CreateSeatParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.CreateSeatRequest != nil {
		if err := r.SetBodyParam(o.CreateSeatRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
