// Code generated by go-swagger; DO NOT EDIT.

package seat_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSeatParams creates a new GetSeatParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSeatParams() *GetSeatParams {
	return &GetSeatParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSeatParamsWithTimeout creates a new GetSeatParams object
// with the ability to set a timeout on a request.
func NewGetSeatParamsWithTimeout(timeout time.Duration) *GetSeatParams {
	return &GetSeatParams{
		timeout: timeout,
	}
}

// NewGetSeatParamsWithContext creates a new GetSeatParams object
// with the ability to set a context for a request.
func NewGetSeatParamsWithContext(ctx context.Context) *GetSeatParams {
	return &GetSeatParams{
		Context: ctx,
	}
}

// NewGetSeatParamsWithHTTPClient creates a new GetSeatParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSeatParamsWithHTTPClient(client *http.Client) *GetSeatParams {
	return &GetSeatParams{
		HTTPClient: client,
	}
}

/* GetSeatParams contains all the parameters to send to the API endpoint
   for the get seat operation.

   Typically these are written to a http.Request.
*/
type GetSeatParams struct {

	/* SeatID.

	   seatId
	*/
	SeatID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get seat params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSeatParams) WithDefaults() *GetSeatParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get seat params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSeatParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get seat params
func (o *GetSeatParams) WithTimeout(timeout time.Duration) *GetSeatParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get seat params
func (o *GetSeatParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get seat params
func (o *GetSeatParams) WithContext(ctx context.Context) *GetSeatParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get seat params
func (o *GetSeatParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get seat params
func (o *GetSeatParams) WithHTTPClient(client *http.Client) *GetSeatParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get seat params
func (o *GetSeatParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSeatID adds the seatID to the get seat params
func (o *GetSeatParams) WithSeatID(seatID string) *GetSeatParams {
	o.SetSeatID(seatID)
	return o
}

// SetSeatID adds the seatId to the get seat params
func (o *GetSeatParams) SetSeatID(seatID string) {
	o.SeatID = seatID
}

// WriteToRequest writes these params to a swagger request
func (o *GetSeatParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param seatId
	if err := r.SetPathParam("seatId", o.SeatID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
