// Code generated by go-swagger; DO NOT EDIT.

package seat_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/isometry/go-digicert-mpki/models"
)

// NewUpdateSeatParams creates a new UpdateSeatParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateSeatParams() *UpdateSeatParams {
	return &UpdateSeatParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateSeatParamsWithTimeout creates a new UpdateSeatParams object
// with the ability to set a timeout on a request.
func NewUpdateSeatParamsWithTimeout(timeout time.Duration) *UpdateSeatParams {
	return &UpdateSeatParams{
		timeout: timeout,
	}
}

// NewUpdateSeatParamsWithContext creates a new UpdateSeatParams object
// with the ability to set a context for a request.
func NewUpdateSeatParamsWithContext(ctx context.Context) *UpdateSeatParams {
	return &UpdateSeatParams{
		Context: ctx,
	}
}

// NewUpdateSeatParamsWithHTTPClient creates a new UpdateSeatParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateSeatParamsWithHTTPClient(client *http.Client) *UpdateSeatParams {
	return &UpdateSeatParams{
		HTTPClient: client,
	}
}

/* UpdateSeatParams contains all the parameters to send to the API endpoint
   for the update seat operation.

   Typically these are written to a http.Request.
*/
type UpdateSeatParams struct {

	/* SeatID.

	   seatId
	*/
	SeatID string

	/* UpdateSeatRequest.

	   updateSeatRequest
	*/
	UpdateSeatRequest *models.UpdateSeatRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update seat params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateSeatParams) WithDefaults() *UpdateSeatParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update seat params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateSeatParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update seat params
func (o *UpdateSeatParams) WithTimeout(timeout time.Duration) *UpdateSeatParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update seat params
func (o *UpdateSeatParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update seat params
func (o *UpdateSeatParams) WithContext(ctx context.Context) *UpdateSeatParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update seat params
func (o *UpdateSeatParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update seat params
func (o *UpdateSeatParams) WithHTTPClient(client *http.Client) *UpdateSeatParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update seat params
func (o *UpdateSeatParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSeatID adds the seatID to the update seat params
func (o *UpdateSeatParams) WithSeatID(seatID string) *UpdateSeatParams {
	o.SetSeatID(seatID)
	return o
}

// SetSeatID adds the seatId to the update seat params
func (o *UpdateSeatParams) SetSeatID(seatID string) {
	o.SeatID = seatID
}

// WithUpdateSeatRequest adds the updateSeatRequest to the update seat params
func (o *UpdateSeatParams) WithUpdateSeatRequest(updateSeatRequest *models.UpdateSeatRequest) *UpdateSeatParams {
	o.SetUpdateSeatRequest(updateSeatRequest)
	return o
}

// SetUpdateSeatRequest adds the updateSeatRequest to the update seat params
func (o *UpdateSeatParams) SetUpdateSeatRequest(updateSeatRequest *models.UpdateSeatRequest) {
	o.UpdateSeatRequest = updateSeatRequest
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateSeatParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param seatId
	if err := r.SetPathParam("seatId", o.SeatID); err != nil {
		return err
	}
	if o.UpdateSeatRequest != nil {
		if err := r.SetBodyParam(o.UpdateSeatRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
