// Code generated by go-swagger; DO NOT EDIT.

package user_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/isometry/go-digicert-mpki/models"
)

// NewCreatePasscodeParams creates a new CreatePasscodeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreatePasscodeParams() *CreatePasscodeParams {
	return &CreatePasscodeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreatePasscodeParamsWithTimeout creates a new CreatePasscodeParams object
// with the ability to set a timeout on a request.
func NewCreatePasscodeParamsWithTimeout(timeout time.Duration) *CreatePasscodeParams {
	return &CreatePasscodeParams{
		timeout: timeout,
	}
}

// NewCreatePasscodeParamsWithContext creates a new CreatePasscodeParams object
// with the ability to set a context for a request.
func NewCreatePasscodeParamsWithContext(ctx context.Context) *CreatePasscodeParams {
	return &CreatePasscodeParams{
		Context: ctx,
	}
}

// NewCreatePasscodeParamsWithHTTPClient creates a new CreatePasscodeParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreatePasscodeParamsWithHTTPClient(client *http.Client) *CreatePasscodeParams {
	return &CreatePasscodeParams{
		HTTPClient: client,
	}
}

/* CreatePasscodeParams contains all the parameters to send to the API endpoint
   for the create passcode operation.

   Typically these are written to a http.Request.
*/
type CreatePasscodeParams struct {

	/* CreatePasscodeRequest.

	   createPasscodeRequest
	*/
	CreatePasscodeRequest *models.CreatePasscodeRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create passcode params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreatePasscodeParams) WithDefaults() *CreatePasscodeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create passcode params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreatePasscodeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create passcode params
func (o *CreatePasscodeParams) WithTimeout(timeout time.Duration) *CreatePasscodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create passcode params
func (o *CreatePasscodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create passcode params
func (o *CreatePasscodeParams) WithContext(ctx context.Context) *CreatePasscodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create passcode params
func (o *CreatePasscodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create passcode params
func (o *CreatePasscodeParams) WithHTTPClient(client *http.Client) *CreatePasscodeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create passcode params
func (o *CreatePasscodeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCreatePasscodeRequest adds the createPasscodeRequest to the create passcode params
func (o *CreatePasscodeParams) WithCreatePasscodeRequest(createPasscodeRequest *models.CreatePasscodeRequest) *CreatePasscodeParams {
	o.SetCreatePasscodeRequest(createPasscodeRequest)
	return o
}

// SetCreatePasscodeRequest adds the createPasscodeRequest to the create passcode params
func (o *CreatePasscodeParams) SetCreatePasscodeRequest(createPasscodeRequest *models.CreatePasscodeRequest) {
	o.CreatePasscodeRequest = createPasscodeRequest
}

// WriteToRequest writes these params to a swagger request
func (o *CreatePasscodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.CreatePasscodeRequest != nil {
		if err := r.SetBodyParam(o.CreatePasscodeRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
