// Code generated by go-swagger; DO NOT EDIT.

package user_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/isometry/go-digicert-mpki/models"
)

// DeleteEnrollmentReader is a Reader for the DeleteEnrollment structure.
type DeleteEnrollmentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteEnrollmentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteEnrollmentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewDeleteEnrollmentNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteEnrollmentUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteEnrollmentForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteEnrollmentOK creates a DeleteEnrollmentOK with default headers values
func NewDeleteEnrollmentOK() *DeleteEnrollmentOK {
	return &DeleteEnrollmentOK{}
}

/* DeleteEnrollmentOK describes a response with status code 200, with default header values.

OK
*/
type DeleteEnrollmentOK struct {
	Payload models.Response
}

func (o *DeleteEnrollmentOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/enrollment/{enrollCode}][%d] deleteEnrollmentOK  %+v", 200, o.Payload)
}
func (o *DeleteEnrollmentOK) GetPayload() models.Response {
	return o.Payload
}

func (o *DeleteEnrollmentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteEnrollmentNoContent creates a DeleteEnrollmentNoContent with default headers values
func NewDeleteEnrollmentNoContent() *DeleteEnrollmentNoContent {
	return &DeleteEnrollmentNoContent{}
}

/* DeleteEnrollmentNoContent describes a response with status code 204, with default header values.

No Content
*/
type DeleteEnrollmentNoContent struct {
}

func (o *DeleteEnrollmentNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/enrollment/{enrollCode}][%d] deleteEnrollmentNoContent ", 204)
}

func (o *DeleteEnrollmentNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteEnrollmentUnauthorized creates a DeleteEnrollmentUnauthorized with default headers values
func NewDeleteEnrollmentUnauthorized() *DeleteEnrollmentUnauthorized {
	return &DeleteEnrollmentUnauthorized{}
}

/* DeleteEnrollmentUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteEnrollmentUnauthorized struct {
}

func (o *DeleteEnrollmentUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/enrollment/{enrollCode}][%d] deleteEnrollmentUnauthorized ", 401)
}

func (o *DeleteEnrollmentUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteEnrollmentForbidden creates a DeleteEnrollmentForbidden with default headers values
func NewDeleteEnrollmentForbidden() *DeleteEnrollmentForbidden {
	return &DeleteEnrollmentForbidden{}
}

/* DeleteEnrollmentForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type DeleteEnrollmentForbidden struct {
}

func (o *DeleteEnrollmentForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/enrollment/{enrollCode}][%d] deleteEnrollmentForbidden ", 403)
}

func (o *DeleteEnrollmentForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
