// Code generated by go-swagger; DO NOT EDIT.

package user_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetEnrollmentParams creates a new GetEnrollmentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetEnrollmentParams() *GetEnrollmentParams {
	return &GetEnrollmentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetEnrollmentParamsWithTimeout creates a new GetEnrollmentParams object
// with the ability to set a timeout on a request.
func NewGetEnrollmentParamsWithTimeout(timeout time.Duration) *GetEnrollmentParams {
	return &GetEnrollmentParams{
		timeout: timeout,
	}
}

// NewGetEnrollmentParamsWithContext creates a new GetEnrollmentParams object
// with the ability to set a context for a request.
func NewGetEnrollmentParamsWithContext(ctx context.Context) *GetEnrollmentParams {
	return &GetEnrollmentParams{
		Context: ctx,
	}
}

// NewGetEnrollmentParamsWithHTTPClient creates a new GetEnrollmentParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetEnrollmentParamsWithHTTPClient(client *http.Client) *GetEnrollmentParams {
	return &GetEnrollmentParams{
		HTTPClient: client,
	}
}

/* GetEnrollmentParams contains all the parameters to send to the API endpoint
   for the get enrollment operation.

   Typically these are written to a http.Request.
*/
type GetEnrollmentParams struct {

	/* EnrollCode.

	   enrollCode
	*/
	EnrollCode string

	/* SeatID.

	   seat_id
	*/
	SeatID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get enrollment params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEnrollmentParams) WithDefaults() *GetEnrollmentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get enrollment params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEnrollmentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get enrollment params
func (o *GetEnrollmentParams) WithTimeout(timeout time.Duration) *GetEnrollmentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get enrollment params
func (o *GetEnrollmentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get enrollment params
func (o *GetEnrollmentParams) WithContext(ctx context.Context) *GetEnrollmentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get enrollment params
func (o *GetEnrollmentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get enrollment params
func (o *GetEnrollmentParams) WithHTTPClient(client *http.Client) *GetEnrollmentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get enrollment params
func (o *GetEnrollmentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnrollCode adds the enrollCode to the get enrollment params
func (o *GetEnrollmentParams) WithEnrollCode(enrollCode string) *GetEnrollmentParams {
	o.SetEnrollCode(enrollCode)
	return o
}

// SetEnrollCode adds the enrollCode to the get enrollment params
func (o *GetEnrollmentParams) SetEnrollCode(enrollCode string) {
	o.EnrollCode = enrollCode
}

// WithSeatID adds the seatID to the get enrollment params
func (o *GetEnrollmentParams) WithSeatID(seatID string) *GetEnrollmentParams {
	o.SetSeatID(seatID)
	return o
}

// SetSeatID adds the seatId to the get enrollment params
func (o *GetEnrollmentParams) SetSeatID(seatID string) {
	o.SeatID = seatID
}

// WriteToRequest writes these params to a swagger request
func (o *GetEnrollmentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param enrollCode
	if err := r.SetPathParam("enrollCode", o.EnrollCode); err != nil {
		return err
	}

	// query param seat_id
	qrSeatID := o.SeatID
	qSeatID := qrSeatID
	if qSeatID != "" {

		if err := r.SetQueryParam("seat_id", qSeatID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
