// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Issuer Issuer
//
// swagger:model Issuer
type Issuer struct {

	// certificate
	// Format: byte
	Certificate strfmt.Base64 `json:"certificate,omitempty"`

	// chain
	Chain []*CertificateInfo `json:"chain"`

	// root
	Root bool `json:"root,omitempty"`

	// serial number
	SerialNumber string `json:"serial_number,omitempty"`

	// subject dn
	SubjectDn string `json:"subject_dn,omitempty"`
}

// Validate validates this issuer
func (m *Issuer) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChain(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Issuer) validateChain(formats strfmt.Registry) error {
	if swag.IsZero(m.Chain) { // not required
		return nil
	}

	for i := 0; i < len(m.Chain); i++ {
		if swag.IsZero(m.Chain[i]) { // not required
			continue
		}

		if m.Chain[i] != nil {
			if err := m.Chain[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("chain" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("chain" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this issuer based on the context it is used
func (m *Issuer) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateChain(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Issuer) contextValidateChain(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Chain); i++ {

		if m.Chain[i] != nil {
			if err := m.Chain[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("chain" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("chain" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Issuer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Issuer) UnmarshalBinary(b []byte) error {
	var res Issuer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
